#!/bin/bash
#ssh -R 0.0.0.0:9000:$1:22 dolev@ansible.cloudlet-dev.com "ansible-playbook /home/dolev/config_BATMAN.yaml -e "ip=$1" > /var/log/ansible/$1"
#export ANSIBLE_CONFIG=/root/ansible/dolev/ansible.cfg
echo $1 > /root/ansible/dolev/inventory
sleep 15
cd /root/ansible/dolev
ansible-playbook /root/ansible/dolev/config_BATMAN.yaml > /var/log/ansible/$1
